openapi: 3.0.1
info:
  title: Payment Service API
  version: 1.0.0
  description: Documentação da API do Payment Service

paths:
  /transactions/{userId}/history:
    get:
      summary: Obtém o histórico de transações do usuário
      parameters:
        - name: userId
          in: path
          description: ID do usuário
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                - id: 1
                  userId: "123e4567-e89b-12d3-a456-426614174001"
                  amount: 100.00
                  timestamp: "2023-01-01T12:00:00"
                  type: RECEIVED

  /transactions/receive-payment:
    post:
      summary: Recebe um pagamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                message: "Payment received successfully"
